# Generated by Django 4.2.15 on 2024-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
